---
# Tasks specific for RedHat systems

- name: RedHat | Set some facts
  set_fact: 
      ansible_distribution: centos
  when: ansible_distribution == "RedHat"

- name: RedHat | Install wazuh repo
  template: src={{ role_path }}/templates/etc-yum.repos.d-rhel.repo.j2
            dest=/etc/yum.repos.d/wazuh.repo
            owner=root
            group=root
            mode=0644

- name: RedHat | Install epel repo
  yum: >
      name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ansible_distribution_major_version}}.noarch.rpm
      state=present

- name: RedHat | Install ossec-hids-agent
  yum: pkg=ossec-hids-agent
       state=present
  tags:
    - init

- name: Create systemd file for ossec-agent
  template: src={{ role_path }}/files/ossec-agent.service
            dest=/usr/lib/systemd/system/ossec-agent.service
            owner=root
            group=root
            mode=0644

- name: Reload system daemon
  shell: systemctl daemon-reload

- name: enable ossec-agent daemon
  shell: systemctl enable ossec-agent